json.id ingredient.id
json.name ingredient.name
json.protein ingredient.protein
json.carbohydrates ingredient.carbohydrates
json.fat ingredient.fat
json.magnesium ingredient.magnesium
json.zinc ingredient.zinc
json.iron ingredient.iron
json.folate ingredient.folate
json.vitamin_d ingredient.vitamin_d